### ISSUE TITLE
Do not update while the mouse is over an edit

### ISSUE THREAD

**Issue by he7d3r** [kenrick95/Raun#16]
The user might be trying to click on a link and the update will make the target to be moved down the page. This is similar to what I reported for [w:en:User talk:Theopolisme/Scripts/ajaxWatchlist.js#Watchlist is reloading while there is user interaction](https://en.wikipedia.org/wiki/User_talk:Theopolisme/Scripts/ajaxWatchlist.js#Watchlist_is_reloading_while_there_is_user_interaction).

The fix would probably be similar to
https://en.wikipedia.org/w/index.php?diff=669250717

**Comment by kenrick95** [comment]
I've implemented "View XX more entries" (like what Facebook/Twitter does to display new entries) in bde6eecfc5bddb1d1ee0c33648b321d759e9a761

I can't deploy this unless [this](https://github.com/Krinkle/intuition/pull/49) got merged and deployed, since this change creates new interface messages.

Hope it helps. Thanks.

**Comment by he7d3r** [comment]
I don't know.. Maybe the button for "More entries" should be displayed only if the mouse is over an item, and keep the old behaviour of loading more edits automatically (as in [mw-gadget-rtrc](https://github.com/Krinkle/mw-gadget-rtrc)). The automatic scrolling is useful when making talks about Wikipedia for a public which do not know that it is edited so frequently. Things like these feeds of edits cause a great impact in the audience :-)

Other option would be to have a new config option: Auto scroll: (Enable/Disable).

And if the option is kept as is, it would be good to avoid the content to scroll down the page when the button appears (e.g. by reserving some white-space in the top, just enough for the button height).

**Comment by kenrick95** [comment]
Good suggestions, thanks, I haven't deploy this new version in Tool Labs; Config option sounds good. Thanks.
