### ISSUE TITLE
Configure for Krinkle/intuition #45

### ISSUE THREAD

**Issue by kenrick95** [kenrick95/Raun#23]
https://github.com/Krinkle/intuition/issues/45#issuecomment-139822029

**Comment by kenrick95** [comment]
Waiting for https://gerrit.wikimedia.org/r/#/c/256442/

**Comment by Nikerabbit** [comment]
Why https://translatewiki.net/w/i.php?title=Intuition:Raun-about_license/en&diff=6572998&oldid=6438641

**Comment by kenrick95** [comment]
Hmmmm I think that's the older messages that got overwritten ._.

**Comment by Nikerabbit** [comment]
Can you re-apply the wording fix in the new repo?

**Comment by kenrick95** [comment]
Okay, I've updated this repo with the latest messages from Krinkle/intuition. (per 775b498e704d76f395d16b81a746a5dcf1edd0d6)
