### ISSUE TITLE
ORES broken

### ISSUE THREAD

**Issue by halfak** [kenrick95/Raun#24]
Looks like you are using [https://ores.wmflabs.org/scores/..wiki](https://ores.wmflabs.org/scores/enwiki/) to find out if a relevant model is supported.  This path used to return a simple list.  Now it returns a map of models to their statistics.  It seems like this has cause ORES integration to fail. 

(Sorry for the lack of a notice about the breaking change.)

**Comment by kenrick95** [comment]
:tada: Thanks for the pull request. No wonder I didn't see ORES score for quite some time. :smile:
